name: 'Save Tag'
description: >
  Saves a tag to the currently checked out ref.  
inputs:
  tag:
    type: string
    description: The tag to add or update.
    required: true

branding:
  icon: 'tag'
  color: 'yellow'

runs:
  using: "composite"
  steps:
    - name: ðŸ·ï¸ Saving Tag ${{ inputs.tag }}
      uses: actions/github-script@v8
      with: 
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ inputs.tag }}',
            sha: context.sha
          }).then(function(result) {
            core.info(`New Tag ${{ inputs.tag }} created`)
          }).catch(err => {
            if (err.status !== 422) throw err;
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ inputs.tag }}',
              sha: context.sha
            });
            core.info(`Tag ${{ inputs.tag }} updated`)
          })